Repository LewerUnlimited/nospoilers, pull requests merged in 2020-02, with the labels that each got.

#2 Feature/1 readme
  README.md
Labels: documentation

#3 restructuring project. new client and api folders. created randomMovie api and hooked it to the front end
  .gitignore
  README.md
  api/app.js
  api/bin/www
  api/package-lock.json
  api/package.json
  api/public/stylesheets/style.css
  api/routes/index.js
  api/routes/randomMovie.js
  api/routes/users.js
  api/views/error.jade
  api/views/index.jade
  api/views/layout.jade
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/setupTests.js
  webapps/my-app/src/App.js
  webapps/my-app/src/App.test.js
Labels: documentation, enhancement

#5 made the button nicer, added react bootsrap, linked button to RandomM…
  client/package-lock.json
  client/package.json
  client/public/nospoilerslogo.png
  client/src/App.js
Labels: bug, enhancement

#6 fixing test and deleting logo
  client/src/App.test.js
  client/src/logo.svg
Labels: bug

#8 Feature/create genres api
  api/app.js
  api/package-lock.json
  api/package.json
  api/routes/genres.js
Labels: enhancement
